---
framework: jest 
preRun:
     command:
        - npm install
preMerge:
  pattern:
    - "./test/*.test.ts"
postMerge:
  pattern: 
    - "./test/*.test.ts"
postRun:
     command:
        - node --version
configFile: jest.config.js
version: 1.0